/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrimmingRouteImport } from './routes/_app/trimming'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppPlaitingRouteImport } from './routes/_app/plaiting'
import { Route as AppOfferingRouteImport } from './routes/_app/offering'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppCashiersRouteImport } from './routes/_app/cashiers'
import { Route as AppAsascoRouteImport } from './routes/_app/asasco'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrimmingRoute = AppTrimmingRouteImport.update({
  id: '/trimming',
  path: '/trimming',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaitingRoute = AppPlaitingRouteImport.update({
  id: '/plaiting',
  path: '/plaiting',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferingRoute = AppOfferingRouteImport.update({
  id: '/offering',
  path: '/offering',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCashiersRoute = AppCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => AppRoute,
} as any)
const AppAsascoRoute = AppAsascoRouteImport.update({
  id: '/asasco',
  path: '/asasco',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asasco': typeof AppAsascoRoute
  '/cashiers': typeof AppCashiersRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/offering': typeof AppOfferingRoute
  '/plaiting': typeof AppPlaitingRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/students': typeof AppStudentsRoute
  '/transactions': typeof AppTransactionsRoute
  '/trimming': typeof AppTrimmingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/asasco': typeof AppAsascoRoute
  '/cashiers': typeof AppCashiersRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/offering': typeof AppOfferingRoute
  '/plaiting': typeof AppPlaitingRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/students': typeof AppStudentsRoute
  '/transactions': typeof AppTransactionsRoute
  '/trimming': typeof AppTrimmingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/asasco': typeof AppAsascoRoute
  '/_app/cashiers': typeof AppCashiersRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/offering': typeof AppOfferingRoute
  '/_app/plaiting': typeof AppPlaitingRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/trimming': typeof AppTrimmingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/asasco'
    | '/cashiers'
    | '/classes'
    | '/dashboard'
    | '/offering'
    | '/plaiting'
    | '/pos'
    | '/products'
    | '/students'
    | '/transactions'
    | '/trimming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/asasco'
    | '/cashiers'
    | '/classes'
    | '/dashboard'
    | '/offering'
    | '/plaiting'
    | '/pos'
    | '/products'
    | '/students'
    | '/transactions'
    | '/trimming'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/asasco'
    | '/_app/cashiers'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/offering'
    | '/_app/plaiting'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/students'
    | '/_app/transactions'
    | '/_app/trimming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trimming': {
      id: '/_app/trimming'
      path: '/trimming'
      fullPath: '/trimming'
      preLoaderRoute: typeof AppTrimmingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plaiting': {
      id: '/_app/plaiting'
      path: '/plaiting'
      fullPath: '/plaiting'
      preLoaderRoute: typeof AppPlaitingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offering': {
      id: '/_app/offering'
      path: '/offering'
      fullPath: '/offering'
      preLoaderRoute: typeof AppOfferingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashiers': {
      id: '/_app/cashiers'
      path: '/cashiers'
      fullPath: '/cashiers'
      preLoaderRoute: typeof AppCashiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asasco': {
      id: '/_app/asasco'
      path: '/asasco'
      fullPath: '/asasco'
      preLoaderRoute: typeof AppAsascoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAsascoRoute: typeof AppAsascoRoute
  AppCashiersRoute: typeof AppCashiersRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOfferingRoute: typeof AppOfferingRoute
  AppPlaitingRoute: typeof AppPlaitingRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTrimmingRoute: typeof AppTrimmingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAsascoRoute: AppAsascoRoute,
  AppCashiersRoute: AppCashiersRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOfferingRoute: AppOfferingRoute,
  AppPlaitingRoute: AppPlaitingRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTrimmingRoute: AppTrimmingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
